config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy ]

  # GET /kittens or /kittens.json
  def index
    @kittens = Kitten.all
  end

  # GET /kittens/1 or /kittens/1.json
  def show
  end

  # GET /kittens/new
  def new
    @kitten = Kitten.new
  end

  # GET /kittens/1/edit
  def edit
  end

  # POST /kittens or /kittens.json
  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to kitten_url(@kitten), notice: "Meow! Kitten was successfully created." }
        format.json { render :show, status: :created, location: @kitten }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kittens/1 or /kittens/1.json
  def update
    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to kitten_url(@kitten), notice: "Meow! Kitten was successfully updated." }
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kittens/1 or /kittens/1.json
  def destroy
    @kitten.destroy

    respond_to do |format|
      format.html { redirect_to kittens_url, notice: "Kitten was successfully destroyed :(" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: kitten) do |form| %>
  <% if kitten.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% kitten.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness, style: "display: block" %>
    <%= form.text_field :cuteness %>
  </div>

  <div>
    <%= form.label :softness, style: "display: block" %>
    <%= form.text_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/_kitten.html.erb
<div id="<%= dom_id kitten %>">
  <p>
    <strong>Name:</strong>
    <%= kitten.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= kitten.age %>
  </p>

  <p>
    <strong>Cuteness:</strong>
    <%= kitten.cuteness %>
  </p>

  <p>
    <strong>Softness:</strong>
    <%= kitten.softness %>
  </p>

</div>

app/views/kittens/edit.html.erb
<h1>Editing kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Show this kitten", @kitten %> |
  <%= link_to "Back to kittens", kittens_path %>
</div>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<div id="kittens">
  <% @kittens.each do |kitten| %>
    <%= render kitten %>
    <p>
      <%= link_to "Show this kitten", kitten %>
    </p>
  <% end %>
</div>

<%= link_to "New kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Back to kittens", kittens_path %>
</div>

app/views/kittens/show.html.erb
<%= render @kitten %>

<div>
  <%= link_to "Edit this kitten", edit_kitten_path(@kitten) %> |
  <%= link_to "Back to kittens", kittens_path %>

  <%= button_to "Destroy this kitten", @kitten, method: :delete %>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="message">
    <% flash.each do |name, message| %>
      <div class="<%= name %>"><%= message %></div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>